const BREAD_LIST_WRITE = [
  "어니언",
  "바질",
  "호두파운드",
  "크림치즈",
  "쉘브론",
  "소보로롤",
  "마블롤",
  "블베카스",
  "모카네오",
  "약밤",
  "레몬롤",
  "쇼콜라",
  "나가사키",
  "호두타르트(일)",
  "호두타르트(프)",
  "미니머핀",
  "구운도넛",
  "레몬케익",
  "시몬(신)",
  "미니머핀(쇼)",
  "레몬케익(쇼)",
  "구운도넛(쇼)",
  "레몬롤(쇼)",
  "마늘빵",
  "퀸아망",
  "아몬드크로아상",
  "구리볼",
  "시몬",
  "블베쉬폰",
  "마블롤(진)",
  "소보로롤(진)",
  "쇼콜라(진)",
  "호두파운드(진)",
  "크림치즈(진)",
  "쉘브론(진)",
  "약밤(진)",
  "블베카스(진)",
  "모카네오(진)",
  "구운도넛(샌)",
  "레몬케익(샌)",
  "나가사키(샌)",
];

const BREAD_LIST_READ = [
  "구리볼",
  "나가사키",
  "나가사키(샌)",
  "레몬롤",
  "레몬롤(쇼)",
  "마블롤",
  "마블롤(진)",
  "모카네오",
  "모카네오(진)",
  "미니머핀",
  "미니머핀(쇼)",
  "블베쉬폰",
  "블베카스",
  "블베카스(진)",
  "소보로롤",
  "소보로롤(진)",
  "쇼콜라",
  "쇼콜라(진)",
  "쉘브론",
  "쉘브론(진)",
  "시몬(신)",
  "시몬",
  "약밤",
  "약밤(진)",
  "크림치즈",
  "크림치즈(진)",
  "마늘빵",
  "호두파운드",
  "호두파운드(진)",
  "구운도넛",
  "구운도넛(쇼)",
  "구운도넛(샌)",
  "레몬케익",
  "레몬케익(쇼)",
  "레몬케익(샌)",
  "어니언",
  "바질",
  "아몬드크로아상",
  "퀸아망",
  "호두타르트(일)",
  "호두타르트(프)",
];

export const BREAD_LIST = [
  {
    name: "호두파운드",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "호두파운드"),
    read: BREAD_LIST_READ.findIndex((b) => b === "호두파운드"),
    quantity: 0,
  },
  {
    name: "크림치즈",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "크림치즈"),
    read: BREAD_LIST_READ.findIndex((b) => b === "크림치즈"),
    quantity: 0,
  },
  {
    name: "쉘브론",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "쉘브론"),
    read: BREAD_LIST_READ.findIndex((b) => b === "쉘브론"),
    quantity: 0,
  },
  {
    name: "소보로롤",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "소보로롤"),
    read: BREAD_LIST_READ.findIndex((b) => b === "소보로롤"),
    quantity: 0,
  },
  {
    name: "마블롤",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "마블롤"),
    read: BREAD_LIST_READ.findIndex((b) => b === "마블롤"),
    quantity: 0,
  },
  {
    name: "블베카스",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "블베카스"),
    read: BREAD_LIST_READ.findIndex((b) => b === "블베카스"),
    quantity: 0,
  },
  {
    name: "모카네오",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "모카네오"),
    read: BREAD_LIST_READ.findIndex((b) => b === "모카네오"),
    quantity: 0,
  },
  {
    name: "약밤",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "약밤"),
    read: BREAD_LIST_READ.findIndex((b) => b === "약밤"),
    quantity: 0,
  },
  {
    name: "레몬롤",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "레몬롤"),
    read: BREAD_LIST_READ.findIndex((b) => b === "레몬롤"),
    quantity: 0,
  },
  {
    name: "쇼콜라",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "쇼콜라"),
    read: BREAD_LIST_READ.findIndex((b) => b === "쇼콜라"),
    quantity: 0,
  },
  {
    name: "나가사키",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "나가사키"),
    read: BREAD_LIST_READ.findIndex((b) => b === "나가사키"),
    quantity: 0,
  },
  {
    name: "어니언",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "어니언"),
    read: BREAD_LIST_READ.findIndex((b) => b === "어니언"),
    quantity: 0,
  },
  {
    name: "바질",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "바질"),
    read: BREAD_LIST_READ.findIndex((b) => b === "바질"),
    quantity: 0,
  },
  {
    name: "호두타르트(일)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "호두타르트(일)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "호두타르트(일)"),
    quantity: 0,
  },
  {
    name: "호두타르트(프)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "호두타르트(프)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "호두타르트(프)"),
    quantity: 0,
  },
  {
    name: "미니머핀",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "미니머핀"),
    read: BREAD_LIST_READ.findIndex((b) => b === "미니머핀"),
    quantity: 0,
  },
  {
    name: "구운도넛",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "구운도넛"),
    read: BREAD_LIST_READ.findIndex((b) => b === "구운도넛"),
    quantity: 0,
  },
  {
    name: "레몬케익",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "레몬케익"),
    read: BREAD_LIST_READ.findIndex((b) => b === "레몬케익"),
    quantity: 0,
  },
  {
    name: "시몬(신)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "시몬(신)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "시몬(신)"),
    quantity: 0,
  },
  {
    name: "미니머핀(쇼)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "미니머핀(쇼)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "미니머핀(쇼)"),
    quantity: 0,
  },
  {
    name: "레몬케익(쇼)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "레몬케익(쇼)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "레몬케익(쇼)"),
    quantity: 0,
  },
  {
    name: "구운도넛(쇼)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "구운도넛(쇼)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "구운도넛(쇼)"),
    quantity: 0,
  },
  {
    name: "레몬롤(쇼)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "레몬롤(쇼)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "레몬롤(쇼)"),
    quantity: 0,
  },
  {
    name: "마늘빵",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "마늘빵"),
    read: BREAD_LIST_READ.findIndex((b) => b === "마늘빵"),
    quantity: 0,
  },
  {
    name: "퀸아망",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "퀸아망"),
    read: BREAD_LIST_READ.findIndex((b) => b === "퀸아망"),
    quantity: 0,
  },
  {
    name: "아몬드크로아상",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "아몬드크로아상"),
    read: BREAD_LIST_READ.findIndex((b) => b === "아몬드크로아상"),
    quantity: 0,
  },
  {
    name: "구리볼",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "구리볼"),
    read: BREAD_LIST_READ.findIndex((b) => b === "구리볼"),
    quantity: 0,
  },
  {
    name: "시몬",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "시몬"),
    read: BREAD_LIST_READ.findIndex((b) => b === "시몬"),
    quantity: 0,
  },
  {
    name: "블베쉬폰",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "블베쉬폰"),
    read: BREAD_LIST_READ.findIndex((b) => b === "블베쉬폰"),
    quantity: 0,
  },
  {
    name: "마블롤(진)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "마블롤(진)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "마블롤(진)"),
    quantity: 0,
  },
  {
    name: "소보로롤(진)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "소보로롤(진)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "소보로롤(진)"),
    quantity: 0,
  },
  {
    name: "쇼콜라(진)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "쇼콜라(진)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "쇼콜라(진)"),
    quantity: 0,
  },
  {
    name: "호두파운드(진)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "호두파운드(진)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "호두파운드(진)"),
    quantity: 0,
  },
  {
    name: "크림치즈(진)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "크림치즈(진)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "크림치즈(진)"),
    quantity: 0,
  },
  {
    name: "쉘브론(진)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "쉘브론(진)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "쉘브론(진)"),
    quantity: 0,
  },
  {
    name: "약밤(진)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "약밤(진)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "약밤(진)"),
    quantity: 0,
  },
  {
    name: "블베카스(진)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "블베카스(진)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "블베카스(진)"),
    quantity: 0,
  },
  {
    name: "모카네오(진)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "모카네오(진)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "모카네오(진)"),
    quantity: 0,
  },
  {
    name: "구운도넛(샌)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "구운도넛(샌)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "구운도넛(샌)"),
    quantity: 0,
  },
  {
    name: "레몬케익(샌)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "레몬케익(샌)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "레몬케익(샌)"),
    quantity: 0,
  },
  {
    name: "나가사키(샌)",
    write: BREAD_LIST_WRITE.findIndex((b) => b === "나가사키(샌)"),
    read: BREAD_LIST_READ.findIndex((b) => b === "나가사키(샌)"),
    quantity: 0,
  },
];
