export const BREAD_LIST_FRIDGE = [
  "어니언",
  "바질",
  "호두파운드",
  "크림치즈",
  "쉘브론",
  "소보로롤",
  "마블롤",
  // "블베카스",
  "모카네오",
  "약밤",
  "레몬롤",
  "쇼콜라",
  "나가사키",
  "호두타르트(일)",
  "호두타르트(프)",
  "미니머핀",
  "구운도넛",
  "레몬케익",
  "시몬(카트)",
  "미니머핀(쇼케)",
  "레몬케익(쇼케)",
  "구운도넛(쇼케)",
  "레몬롤(쇼케)",
  "마늘빵",
  "퀸아망",
  "아몬드크로아상",
  "구리볼",
  "시몬",
  "블베쉬폰",
  "마블롤(진열)",
  "소보로롤(진열)",
  "쇼콜라(진열)",
  "호두파운드(진열)",
  "크림치즈(진열)",
  "쉘브론(진열)",
  "약밤(진열)",
  // "블베카스(진열)",
  "모카네오(진열)",
  "구운도넛(샌드)",
  "레몬케익(샌드)",
  "나가사키(샌드)",
];

export const BREAD_LIST_CHECKLIST = [
  "구리볼",
  "나가사키",
  "나가사키(샌드)",
  "레몬롤",
  "레몬롤(쇼케)",
  "마블롤",
  "마블롤(진열)",
  "모카네오",
  "모카네오(진열)",
  "미니머핀",
  "미니머핀(쇼케)",
  "블베쉬폰",
  // "블베카스",
  // "블베카스(진열)",
  "소보로롤",
  "소보로롤(진열)",
  "쇼콜라",
  "쇼콜라(진열)",
  "쉘브론",
  "쉘브론(진열)",
  "시몬(카트)",
  "시몬",
  "약밤",
  "약밤(진열)",
  "크림치즈",
  "크림치즈(진열)",
  "마늘빵",
  "호두파운드",
  "호두파운드(진열)",
  "구운도넛",
  "구운도넛(쇼케)",
  "구운도넛(샌드)",
  "레몬케익",
  "레몬케익(쇼케)",
  "레몬케익(샌드)",
  "어니언",
  "바질",
  "아몬드크로아상",
  "퀸아망",
  "호두타르트(일)",
  "호두타르트(프)",
];

export const BREAD_LIST = [
  {
    no: 1,
    name: "호두파운드",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "호두파운드"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "호두파운드"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "호두파운드.jpg",
  },
  {
    no: 2,
    name: "크림치즈",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "크림치즈"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "크림치즈"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "크림치즈.jpg",
  },
  {
    no: 3,
    name: "쉘브론",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "쉘브론"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "쉘브론"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "쉘브론.jpg",
  },
  {
    no: 4,
    name: "소보로롤",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "소보로롤"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "소보로롤"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "소보로롤.jpg",
  },
  {
    no: 5,
    name: "마블롤",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "마블롤"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "마블롤"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "마블롤.jpg",
  },
  // {
  //   no: 6,
  //   name: "블베카스",
  //   fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "블베카스"),
  //   checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "블베카스"),
  //   quantity: 0,
  //   label: "",
  //   canCopy: true,
  //   img: "블베카스.jpg",
  // },
  {
    no: 7,
    name: "모카네오",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "모카네오"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "모카네오"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "모카네오.jpg",
  },
  {
    no: 8,
    name: "약밤",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "약밤"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "약밤"),
    quantity: 0,
    label: "White",
    canCopy: true,
    img: "약밤.jpg",
  },
  {
    no: 9,
    name: "레몬롤",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "레몬롤"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "레몬롤"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "레몬롤.jpg",
  },
  {
    no: 10,
    name: "쇼콜라",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "쇼콜라"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "쇼콜라"),
    quantity: 0,
    label: "왼쪽",
    canCopy: true,
    img: "쇼콜라.jpg",
  },
  {
    no: 11,
    name: "나가사키",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "나가사키"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "나가사키"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "나가사키.jpg",
  },
  {
    no: 12,
    name: "어니언",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "어니언"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "어니언"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "어니언.jpg",
  },
  {
    no: 13,
    name: "바질",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "바질"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "바질"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "바질.jpg",
  },
  {
    no: 14,
    name: "호두타르트(일)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "호두타르트(일)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "호두타르트(일)"),
    quantity: 0,
    label: "",
    canCopy: false,
    img: "호두타르트(일).jpg",
  },
  {
    no: 15,
    name: "호두타르트(프)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "호두타르트(프)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "호두타르트(프)"),
    quantity: 0,
    label: "",
    canCopy: false,
    img: "호두타르트(프).jpg",
  },
  {
    no: 16,
    name: "미니머핀",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "미니머핀"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "미니머핀"),
    quantity: 0,
    label: "정방향",
    canCopy: true,
    img: "미니머핀.jpg",
  },
  {
    no: 17,
    name: "구운도넛",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "구운도넛"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "구운도넛"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "구운도넛.jpg",
  },
  {
    no: 18,
    name: "레몬케익",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "레몬케익"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "레몬케익"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "레몬케익.jpg",
  },
  {
    no: 19,
    name: "시몬(카트)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "시몬(카트)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "시몬(카트)"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "시몬(카트).jpg",
  },
  {
    no: 16,
    name: "미니머핀(쇼케)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "미니머핀(쇼케)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "미니머핀(쇼케)"),
    quantity: 0,
    label: "정방향",
    canCopy: true,
    img: "미니머핀(쇼케).jpg",
  },
  {
    no: 18,
    name: "레몬케익(쇼케)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "레몬케익(쇼케)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "레몬케익(쇼케)"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "레몬케익(쇼케).jpg",
  },
  {
    no: 17,
    name: "구운도넛(쇼케)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "구운도넛(쇼케)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "구운도넛(쇼케)"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "구운도넛(쇼케).jpg",
  },
  {
    no: 9,
    name: "레몬롤(쇼케)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "레몬롤(쇼케)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "레몬롤(쇼케)"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "레몬롤(쇼케).jpg",
  },
  {
    no: 20,
    name: "마늘빵",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "마늘빵"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "마늘빵"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "마늘빵.jpg",
  },
  {
    no: 21,
    name: "퀸아망",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "퀸아망"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "퀸아망"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "퀸아망.jpg",
  },
  {
    no: 22,
    name: "아몬드크로아상",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "아몬드크로아상"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "아몬드크로아상"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "아몬드크로아상.jpg",
  },
  {
    no: 23,
    name: "구리볼",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "구리볼"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "구리볼"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "구리볼.jpg",
  },
  {
    no: 19,
    name: "시몬",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "시몬"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "시몬"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "시몬.jpg",
  },
  {
    no: 24,
    name: "블베쉬폰",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "블베쉬폰"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "블베쉬폰"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "블베쉬폰.jpg",
  },
  {
    no: 5,
    name: "마블롤(진열)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "마블롤(진열)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "마블롤(진열)"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "마블롤(진열).jpg",
  },
  {
    no: 4,
    name: "소보로롤(진열)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "소보로롤(진열)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "소보로롤(진열)"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "소보로롤(진열).jpg",
  },
  {
    no: 10,
    name: "쇼콜라(진열)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "쇼콜라(진열)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "쇼콜라(진열)"),
    quantity: 0,
    label: "왼쪽",
    canCopy: true,
    img: "쇼콜라(진열).jpg",
  },
  {
    no: 1,
    name: "호두파운드(진열)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "호두파운드(진열)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "호두파운드(진열)"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "호두파운드(진열).jpg",
  },
  {
    no: 2,
    name: "크림치즈(진열)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "크림치즈(진열)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "크림치즈(진열)"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "크림치즈(진열).jpg",
  },
  {
    no: 3,
    name: "쉘브론(진열)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "쉘브론(진열)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "쉘브론(진열)"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "쉘브론(진열).jpg",
  },
  {
    no: 8,
    name: "약밤(진열)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "약밤(진열)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "약밤(진열)"),
    quantity: 0,
    label: "White",
    canCopy: true,
    img: "약밤(진열).jpg",
  },
  // {
  //   no: 6,
  //   name: "블베카스(진열)",
  //   fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "블베카스(진열)"),
  //   checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "블베카스(진열)"),
  //   quantity: 0,
  //   label: "",
  //   canCopy: true,
  //   img: "블베카스(진열).jpg",
  // },
  {
    no: 7,
    name: "모카네오(진열)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "모카네오(진열)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "모카네오(진열)"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "모카네오(진열).jpg",
  },
  {
    no: 17,
    name: "구운도넛(샌드)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "구운도넛(샌드)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "구운도넛(샌드)"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "구운도넛(샌드).jpg",
  },
  {
    no: 18,
    name: "레몬케익(샌드)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "레몬케익(샌드)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "레몬케익(샌드)"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "레몬케익(샌드).jpg",
  },
  {
    no: 11,
    name: "나가사키(샌드)",
    fridge: BREAD_LIST_FRIDGE.findIndex((b) => b === "나가사키(샌드)"),
    checklist: BREAD_LIST_CHECKLIST.findIndex((b) => b === "나가사키(샌드)"),
    quantity: 0,
    label: "",
    canCopy: true,
    img: "나가사키(샌드).jpg",
  },
];
